# Generated by Django 3.2.7 on 2021-12-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='upadate',
            new_name='update',
        ),
    ]
